sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# This is needed to make mininet available to virtualenv
virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libsuitesparse-dev
    - libgdal-dev
    - graphviz
    - mono-devel
    - mininet

before_install:
  - uname -a
  - printenv

install:
  - travis wait 30 make install # Building Scipy from sources on Python 2.7 takes more than 10 minutes

script:
  - make test
