language: python

# Python versions to be tested
python:
  - "2.7"
  - "3.2"
  - "3.3"

env:
  global:
    - PIP_WHEEL_INSTALL="pip install --quiet --use-wheel --no-index --find-links=http://sunpy.cadair.com/wheelhouse/"
    - PIP_INSTALL="pip install --quiet --upgrade"

before_install:
  - $PIP_INSTALL setuptools
  - $PIP_INSTALL pip
  - $PIP_INSTALL wheel

install:
  # For Ubuntu 12.04 VMs
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran clang ant doxygen
  - $PIP_WHEEL_INSTALL numpy scipy matplotlib
  - $PIP_INSTALL networkx

before_script:
  - $PIP_WHEEL_INSTALL nose

# command to run tests
script:
  - make test